accent = "#ae803c"
active_border_color = "#c1c2c4"
active_tab_background = "#ae803c"

# Cursor colors
cursor = "#c1c2c4"

# Primary colors
foreground = "#c1c2c4"
background = "#030c17"

# Selection colors
selection_foreground = "#030c17"
selection_background = "#ae803c"

# Normal colors (ANSI 0-7)
color0  = "#030c17"
color1  = "#b17d53"
color2  = "#eb5808"
color3  = "#bb793e"
color4  = "#ae803c"
color5  = "#b87d25"
color6  = "#8476fa"
color7  = "#8c9296"

# Bright colors (ANSI 8-15)
color8  = "#558bcb"
color9  = "#b47b54"
color10 = "#ea5808"
color11 = "#b97b3e"
color12 = "#c4914b"
color13 = "#e9a53f"
color14 = "#8775f7"
color15 = "#c1c2c4"
