# exec-once = [workspace special:notes silent] obsidian
# exec-once = [workspace special:music silent] fooyin
exec-once = wal -R
exec-once = sleep 2 && waybar
exec-once = nm-applet
exec-once = sleep 4 && copyq --start-server
exec-once = udiskie
exec-once = swaync
exec-once = swaync-client -df

exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
exec-once = hypridle
