# exec-once = [workspace special:notes silent] obsidian
# exec-once = [workspace special:music silent] fooyin
exec-once = copyq --start-server
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
exec-once = nm-applet
exec-once = hypridle

# Notification center
exec-once = swaync

exec-once = sleep 2 && waybar
