timeout = 2000
; Timeout after which wob hides itself, in milliseconds.
max = 100
; This value will be represented as fully filled bar.
width = 380
; Width of wob, in pixels.
height = 28
; Height of wob, in pixels.
border_offset = 0
; Border offset, in pixels.
border_size = 6
; Border size, in pixels.
bar_padding = 3
; Bar padding, in pixels.
anchor = bottom
; Anchor point, combination of top, left, right, bottom, center.
; Example: bottom right
margin = 18 
; Anchor margin, in pixels. Either as a single value or 4 values (top right bottom left).
border_color = 0B0909DD
; Border color, in RRGGBB[AA] format.
background_color = 1c1c1cDD
; Background color, in RRGGBB[AA] format.
bar_color = EEEEEEFF
; Bar color, in RRGGBB[AA] format.
overflow_mode = wrap
; Overflow mode, one of wrap, and nowrap.
; wrap: wrap value so max + 20 will be displayed as 20
; nowrap values > max will be displayed as just max
overflow_bar_color = b30000 
; Overflow bar color, in RRGGBB[AA] format.
overflow_background_color = 1c1c1cDD
; Overflow background color, in RRGGBB[AA] format.
overflow_border_color = 000000FF 
; Overflow border color, in RRGGBB[AA] format.
orientation = horizontal
; Orientation of the bar, one of horizontal and vertical.
; width and height is kept as is, you most likely want to set height greater than width in vertical mode

[style.br]
bar_color = ffb84dDD

[style.mut]
bar_color = EEEEEE77

[style.mic-mut]
bar_color = 1A487077

[style.mic]
bar_color = 5B99C277
